# TUMHARI WATCHLIST SECTORS
SECTOR_INDEX = {
    "PHARMA": "^CNXPHARMA",        # NIFTY PHARMA
    "AUTO": "^CNXAUTO",            # NIFTY AUTO
    "ENERGY": "^CNXENERGY",        # NIFTY ENERGY
    "PVT BANK": "^NSEBANK",        # NIFTY PVT BANK (Yahoo pe BANK index hi hai)
    "FMCG": "^CNXFMCG",            # NIFTY FMCG
    "OIL AND GAS": "^CNXOIL",      # NIFTY OIL AND GAS
    "IT": "^CNXIT",
    "METAL": "^CNXMETAL",
    "REALTY": "^CNXREALTY",
    "DEFENCE": "HAL.NS",           # Defence ka index nahi hai
}

STOCKS = {
    "PHARMA": ["SUNPHARMA.NS","DIVISLAB.NS","CIPLA.NS","DRREDDY.NS","LUPIN.NS"],
    "AUTO": ["MARUTI.NS","TATAMOTORS.NS","M&M.NS","EICHERMOT.NS","BAJAJ-AUTO.NS"],
    "ENERGY": ["RELIANCE.NS","NTPC.NS","ONGC.NS","POWERGRID.NS","ADANIGREEN.NS"],
    "PVT BANK": ["HDFCBANK.NS","ICICIBANK.NS","KOTAKBANK.NS","AXISBANK.NS","INDUSINDBK.NS"],
    "FMCG": ["ITC.NS","HINDUNILVR.NS","NESTLEIND.NS","BRITANNIA.NS"],
    "OIL AND GAS": ["RELIANCE.NS","ONGC.NS","BPCL.NS","IOC.NS"],
    "IT": ["TCS.NS","INFY.NS","WIPRO.NS"],
    "METAL": ["TATASTEEL.NS","JSWSTEEL.NS","HINDALCO.NS"],
    "REALTY": ["DLF.NS","GODREJPROP.NS"],
    "DEFENCE": ["HAL.NS","BEL.NS","SOLARINDS.NS","MAZDOCK.NS","BEML.NS"],
}
